name: MaH Webb

description: MaH Webb

author:
    name: Sebastian Bengtegård

url: http://mah-webb.github.io

highlighter: pygments

exclude: ['Gemfile', 'Gemfile.lock', 'README.md']

include: ['.htaccess']

defaults:
    -
        scope:
            path: ""
            type: "page"
        values:
            layout: "default"
    -
        scope:
            path: ""
            type: "post"
        values:
            layout: "blog"
