name: Mah Webb

description: Mah Webb

github: https://github.com/mah-webb/mah-webb.github.io

analytics: UA-48530327-3

author:
    name: Sebastian Bengtegård

url: http://mah-webb.github.io

highlighter: pygments

markdown: kramdown

exclude: ['Gemfile', 'Gemfile.lock', 'README.md']

include: ['.htaccess']

permalink: /blog/:categories/:title.html

paginate: 5
paginate_path: /blog/page:num
